#include "Carre.h"




void Carre::Carre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A53 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A53 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Carre::Carre(Point2D A, Point2D B, Point2D C, Point2D D)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A58 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A58 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Carre::Carre(Segment segment)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A5E begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A5E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Carre::estCarre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A6F begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A6F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
