#include "Cercle.h"




void Cercle::Cercle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009D2 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009D2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cercle::Cercle(Point2D point)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009D4 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009D4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cercle::Cercle(Point2D point, Integer rayon)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009D7 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009D7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Integer Cercle::getRayon()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009DB begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009DB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cercle::setRayon(Integer rayon)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009DD begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009DD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cercle::affiche()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009E0 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009E0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cercle::translation(Point2D point)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009E2 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009E2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
