#include "Equilateral.h"




void Equilateral::Equilateral()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A80 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A80 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Equilateral::Equilateral(Point2D A, Point2D B, Point2D C)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A82 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A82 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Equilateral::Equilateral(Segment base, Point2D point)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A87 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A87 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Boolean Equilateral::estEquilateral()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A8B begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A8B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
