#include "Figure.h"




void Figure::Figure()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:000000000000098C begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:000000000000098C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Figure::Figure(Integer x, Integer y)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:000000000000098E begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:000000000000098E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Figure::Figure(Point2D point)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000992 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000992 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Figure::translation(Point2D point)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000995 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000995 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Figure::affiche()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000998 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000998 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Point2D Figure::getA()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009AF begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009AF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Figure::setA(Point2D A)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009B1 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009B1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
