#include "Isocele.h"




void Isocele::Isocele()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A73 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A73 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Isocele::Isocele(Point2D A, Point2D B, Point2D C)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A75 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A75 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Isocele::Isocele(Segment base, Point2D point)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A7A begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A7A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Boolean Isocele::estIsocele()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A7E begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A7E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
