#include "Losange.h"




void Losange::Losange()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A61 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A61 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Losange::Losange(Point2D A, Point2D B, Point2D C, Point2D D)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A63 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A63 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Losange::Losange(Segment segmentLong, Segment segmentLar)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A69 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A69 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Boolean Losange::estLosange()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A71 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A71 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
