#include "Parallelogramme.h"




void Parallelogramme::Parallelogramme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A39 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A39 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Parallelogramme::Parallelogramme(Point2D A, Point2D B, Point2D C, Point2D D)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A3B begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A3B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Parallelogramme::Parallelogramme(Segment segmentLong, Segment segmentLar)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A41 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A41 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Boolean Parallelogramme::estParallelogramme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A45 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A45 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
