#include "Point2D.h"




void Point2D::Point2D()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000969 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000969 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Point2D::Point2D(Integer x, Integer y)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:000000000000096B begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:000000000000096B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Integer Point2D::getX()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000973 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000973 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Integer Point2D::getY()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000978 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000978 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Point2D::setX(Integer x)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:000000000000097A begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:000000000000097A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Point2D::setY(Integer y)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000983 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000983 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Boolean Point2D::estIdentique()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000986 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000986 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
