#include "Quadrilatere.h"




void Quadrilatere::Quadrilatere()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A09 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A09 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Quadrilatere::Quadrilatere(Point2D A, Point2D B, Point2D C, Quadrilatere D)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A0B begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A0B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Point2D Quadrilatere::getC()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A19 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A19 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Point2D Quadrilatere::getD()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A1E begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A1E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Quadrilatere::setC(Point2D C)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A20 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A20 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Quadrilatere::setD(Point2D D)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A23 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A23 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Quadrilatere::affiche()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A26 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A26 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Quadrilatere::translation(Point2D point)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A28 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A28 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
