#include "Quadrangle.h"




void Quadrangle::Quadrangle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--4e0d96dc:141a63f329e:-8000:0000000000000C91 begin
{
}
// section 10-14-23-111--4e0d96dc:141a63f329e:-8000:0000000000000C91 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Quadrangle::Quadrangle(Point2D A, Point2D B, Point2D C, Point2D D)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--4e0d96dc:141a63f329e:-8000:0000000000000C93 begin
{
}
// section 10-14-23-111--4e0d96dc:141a63f329e:-8000:0000000000000C93 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Boolean Quadrangle::estQuadrangle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--4e0d96dc:141a63f329e:-8000:0000000000000C9C begin
{
}
// section 10-14-23-111--4e0d96dc:141a63f329e:-8000:0000000000000C9C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
