#include "Rectangle.h"




void Rectangle::Rectangle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A47 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Rectangle::Rectangle(Point2D A, Point2D B, Point2D C, Point2D D)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A49 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A49 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Rectangle::Rectangle(Segment segmentLong, Segment segmentLar)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A4F begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A4F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Boolean Rectangle::estRectangle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A6D begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A6D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
