#include "Segment.h"




void Segment::Segment()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009A1 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009A1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Segment::Segment(Point2D A)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009A3 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009A3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Segment::Segment(Point2D A, Point2D B)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009A6 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009A6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Point2D Segment::getB()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009AA begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009AA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Segment::setB()(Point2D B)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009B4 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009B4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Segment::affiche()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009B7 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009B7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Segment::translation(Point2D point)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009B9 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009B9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Boolean Segment::estPerpendiculaire(Segment segment)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009BC begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009BC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Boolean Segment::estParallele(Segment segment)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009C0 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009C0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Boolean Segment::seCoupe(Segment segment)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009C3 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009C3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
