#include "TRectangle.h"




void TRectangle::TRectangle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A8D begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A8D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void TRectangle::TRectangle(Point2D A, Point2D B, Point2D C)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A8F begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A8F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void TRectangle::TRectangle(Segment base, Point2D point )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A94 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A94 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Boolean TRectangle::estTRectangle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A98 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A98 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
