#include "Triangle.h"




void Triangle::Triangle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009EF begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009EF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Triangle::Triangle(Point2D A, Point2D B, Point2D C)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009F4 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009F4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Triangle::Triangle(Segment base, Point2D point)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009F9 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009F9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Point2D Triangle::getC()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009FD begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009FD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Triangle::setC(Point2D C)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009FF begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:00000000000009FF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Triangle::affiche()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A02 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A02 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Triangle::translation(Point2D point)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A04 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A04 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Boolean Triangle::estPlat()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A07 begin
{
}
// section 10-14-23-111--25f89f4:1419ce2a8ea:-8000:0000000000000A07 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
